version: 0.0
os: linux
hooks:
  BeforeInstall:
    - location: install.sh
      timeout: 300
      runas: root
  ValidateService:
    - location: validate.sh
      timeout: 60
      runas: root
